"C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\Scripts\python.exe" "C:/Users/Mike Nolan/PycharmProjects/WebSaver4/main.py"
https://freenode.logbot.info/grapheneos-offtopic/20210418
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/robots.txt
C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\webpage.py:82: UserWarning: Global Configuration is not setup. You can ignore this if you are going manual.This is just one time warning regarding some unexpected behavior.
  warnings.warn(
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/grapheneos-offtopic/20210418
webpage    - INFO     - Starting save_complete Action on url: ['https://freenode.logbot.info/grapheneos-offtopic/20210418']
parsers    - INFO     - Parsing tree with source: <<urllib3.response.HTTPResponse object at 0x000001AC52216250>> encoding <UTF-8> and parser <<lxml.etree.HTMLParser object at 0x000001AC5174DDC0>>
webpage    - INFO     - Starting save_assets Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210418'
webpage    - Level 100 - Queueing download of <177> asset files.
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/static/logbot.min.css?1532793644
elements   - INFO     - Writing file at location C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\b7aa61d1__logbot.min.css
webpage    - INFO     - Starting save_html Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210418'
webpage    - INFO     - WebPage saved successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\grapheneos-offtopic\d593d446__20210418.html
elements   - INFO     - File of type .css written successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\b7aa61d1__logbot.min.css
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/static/logbot.min.css?1532793644
Exception in thread <Element(LinkTag, https://freenode.logbot.info/static/logbot.min.css?1532793644)>:
Traceback (most recent call last):
  File "C:\Users\Mike Nolan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Mike Nolan\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\elements.py", line 331, in run
    contents = self.replace_urls(req.content, self.repl)
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\elements.py", line 292, in replace_urls
    contents = CSS_URLS_RE.sub(repl, css_string)
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\elements.py", line 273, in repl
    url = pathname2url(relate(new_element.file_path, self.file_path))
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\urls.py", line 438, in relate
    return os.path.join(os.path.relpath(target_dir, start_dir), os.path.basename(target_file))
  File "C:\Users\Mike Nolan\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'A:', start on mount 'C:'
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/static/logbot-favicon.svg?1508070144
elements   - INFO     - Writing file at location C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\ee60dad3__logbot-favicon.svg
elements   - INFO     - File of type .svg written successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\ee60dad3__logbot-favicon.svg
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/static/logbot-favicon.svg?1508070144
elements   - INFO     - [0] CSS linked files are found in file [C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\ee60dad3__logbot-favicon.svg]
elements   - INFO     - File already exists at location: 'C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\ee60dad3__logbot-favicon.svg'
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/static/logbot.min.js?1532949303
elements   - INFO     - Writing file at location C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\88023ef2__logbot.min.js
elements   - INFO     - File of type .js written successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\static\88023ef2__logbot.min.js
https://freenode.logbot.info/grapheneos-offtopic/20210419
core       - INFO     - Saved the Project as ZIP archive at C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs.zip
core       - INFO     - Downloaded Contents Size :: 271 KB's
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/robots.txt
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/grapheneos-offtopic/20210419
webpage    - INFO     - Starting save_complete Action on url: ['https://freenode.logbot.info/grapheneos-offtopic/20210419']
parsers    - INFO     - Parsing tree with source: <<urllib3.response.HTTPResponse object at 0x000001AC52A531C0>> encoding <UTF-8> and parser <<lxml.etree.HTMLParser object at 0x000001AC4F7FCEE0>>
webpage    - INFO     - Starting save_assets Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210419'
webpage    - Level 100 - Queueing download of <195> asset files.
elements   - INFO     - File already exists at location: ['C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\ee60dad3__logbot-favicon.svg']
elements   - INFO     - File already exists at location: ['C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\b7aa61d1__logbot.min.css']
webpage    - INFO     - Starting save_html Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210419'
elements   - INFO     - File already exists at location: 'C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\88023ef2__logbot.min.js'
webpage    - INFO     - WebPage saved successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\grapheneos-offtopic\77c6d3b6__20210419.html
https://freenode.logbot.info/grapheneos-offtopic/20210420
core       - INFO     - Saved the Project as ZIP archive at C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs.zip
core       - INFO     - Downloaded Contents Size :: 306 KB's
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/robots.txt
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/grapheneos-offtopic/20210420
webpage    - INFO     - Starting save_complete Action on url: ['https://freenode.logbot.info/grapheneos-offtopic/20210420']
parsers    - INFO     - Parsing tree with source: <<urllib3.response.HTTPResponse object at 0x000001AC52A554F0>> encoding <UTF-8> and parser <<lxml.etree.HTMLParser object at 0x000001AC5174DDC0>>
webpage    - INFO     - Starting save_assets Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210420'
webpage    - Level 100 - Queueing download of <202> asset files.
elements   - INFO     - File already exists at location: ['C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\ee60dad3__logbot-favicon.svg']
elements   - INFO     - File already exists at location: ['C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\b7aa61d1__logbot.min.css']
webpage    - INFO     - Starting save_html Action on url: 'https://freenode.logbot.info/grapheneos-offtopic/20210420'
elements   - INFO     - File already exists at location: 'C:\\Users\\Mike Nolan\\Documents\\Documents\\Logbot\\Logs\\freenode.logbot.info\\static\\88023ef2__logbot.min.js'
webpage    - INFO     - WebPage saved successfully to C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs\freenode.logbot.info\grapheneos-offtopic\57d23900__20210420.html
https://freenode.logbot.info/grapheneos-offtopic/20210421
core       - INFO     - Saved the Project as ZIP archive at C:\Users\Mike Nolan\Documents\Documents\Logbot\Logs.zip
core       - INFO     - Downloaded Contents Size :: 347 KB's
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/robots.txt
pywebcopy.configs - INFO     - Got response 200 from https://freenode.logbot.info/grapheneos-offtopic/20210421
webpage    - INFO     - Starting save_complete Action on url: ['https://freenode.logbot.info/grapheneos-offtopic/20210421']
parsers    - INFO     - Parsing tree with source: <<urllib3.response.HTTPResponse object at 0x000001AC52A57700>> encoding <UTF-8> and parser <<lxml.etree.HTMLParser object at 0x000001AC4F7FCEE0>>
Traceback (most recent call last):
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\main.py", line 39, in <module>
    save_webpage(url, download_folder, **kwargs)
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\api.py", line 90, in save_webpage
    wp.save_complete()
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\webpage.py", line 286, in save_complete
    self.parse()  # call in the action
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\parsers.py", line 188, in parse
    o = factory(elem, attr, url, pos)
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\elements.py", line 458, in make_element
    rel_path = pathname2url(obj.relative_to(utx.file_path))
  File "C:\Users\Mike Nolan\PycharmProjects\WebSaver4\venv\lib\site-packages\pywebcopy\urls.py", line 421, in relative_to
    rel_path = os.path.relpath(head, start)
  File "C:\Users\Mike Nolan\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'P:', start on mount 'C:'

Process finished with exit code 1
